# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170922_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(blank=True, max_length=300, verbose_name='address1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=300, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='contact_num'),
        ),
    ]
