# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('style_num', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100, unique=True)),
                ('goods_price', models.CharField(max_length=30)),
                ('goods_detail', models.TextField()),
                ('goods_created', models.DateField(auto_now_add=True)),
                ('goods_mainImage', models.ImageField(upload_to='', verbose_name='MainImage')),
                ('goods_subImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage')),
                ('goods_subImage2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SubImage2')),
            ],
        ),
        migrations.CreateModel(
            name='HighCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LowCategory',
            fields=[
                ('group_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('high_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LowCategory', to='mall.HighCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_amount', models.CharField(max_length=100)),
                ('created_order', models.DateField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem', to='mall.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem', to='mall.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(max_length=10)),
                ('color_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='mall.Color')),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='mall.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.IntegerField(default=0)),
                ('color_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='mall.Color')),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='mall.Goods')),
                ('size_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='mall.Size')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='high_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.HighCategory'),
        ),
        migrations.AddField(
            model_name='goods',
            name='low_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.LowCategory'),
        ),
        migrations.AddField(
            model_name='color',
            name='goods_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Color', to='mall.Goods'),
        ),
    ]
