# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('style_num', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_price', models.CharField(max_length=30)),
                ('goods_detail', models.TextField()),
                ('goods_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LowCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('code', models.IntegerField(unique=True)),
                ('high_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LowCategory', to='mall.HighCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Option_1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color_code', models.CharField(max_length=10)),
                ('goods_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Color', to='mall.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Option_2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('size_code', models.CharField(max_length=10)),
                ('size_stock', models.IntegerField(default=0)),
                ('color_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='mall.Option_1')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='high_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.HighCategory'),
        ),
        migrations.AddField(
            model_name='goods',
            name='low_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.LowCategory'),
        ),
    ]
