# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_2',
            name='size_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
