# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
