# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20171213_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_2',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
