# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_remove_highcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowcategory',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
