# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20171212_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowcategory',
            old_name='high_code',
            new_name='high_category',
        ),
    ]
