# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20171212_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_created', models.DateTimeField(auto_created=True)),
                ('style_num', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_price', models.CharField(max_length=30)),
                ('goods_detail', models.TextField()),
                ('goods_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.Size'),
        ),
        migrations.AddField(
            model_name='goods',
            name='high_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.HighCategory'),
        ),
        migrations.AddField(
            model_name='goods',
            name='low_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Goods', to='mall.LowCategory'),
        ),
    ]
