# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_auto_20171212_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_num',
            new_name='color_code',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_num',
            new_name='size_code',
        ),
    ]
