# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_auto_20171212_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highcategory',
            name='gender',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lowcategory',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
