# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_auto_20171212_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
