# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='goods_color',
        ),
        migrations.RemoveField(
            model_name='options',
            name='goods_size',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
